apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sample-deploy
  namespace: test
  labels:
    app: sample-app
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
      limits:
        memory: 128Mi
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - container17
        from:
          kind: ImageStreamTag
          namespace: test
          name: 'osdocker-s2i:latest'
  replicas: 1
  test: false
  selector:
    app: sample-app
    deploymentconfig: sample-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app
        deploymentconfig: sample-deploy
    spec:
      containers:
        -
          args:
            - bash
          name: container17
          image: 'osdocker-s2i:latest'
          resources:
            limits:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          tty: true
          stdin: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
status:
  observedGeneration: 4
